name: CI/CD Pipeline - Dev

on:
  push:
    branches:
      - dev

env:
  AWS_ACCOUNT: 481768428259
  AWS_REGION: "us-east-1"
  APP_NAME: "linuxtips-app"
  CLUSTER_NAME: "linuxtips-cluster-ecs"
  REPOSITORY_NAME: "linuxtips/$APP_NAME"

jobs:
  ci-app:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Goland
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'

    - name: Install Golint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0

    - name: Lint App
      run: golangci-lint run ./... -E errcheck
      working-directory: ./app

    - name: Test App
      run: go test -v ./...
      working-directory: ./app

  ci-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4    
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.7"

    - name: Terraform Format
      run: terraform fmt --recursive --check

    - name: Terraform Init
      run: terraform init -backend-config=environment/${GITHUB_REF_NAME}/backend.tfvars
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION}}

    - name: Terraform Validate
      run: terraform init -backend-config=environment/${GITHUB_REF_NAME}/backend.tfvars
      working-directory: ./terraform      
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION}}

  build-publish:
    runs-on: ubuntu-latest
    needs:
      - ci-app
      - ci-terraform
    steps:
      - name: checkout repository
        uses: actions/checkout@v4  

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:  ${{ env.AWS_REGION }}